name=Patchugo_Lite
version=1.0.0
author=Innuvatech
maintainer=Innuvatech <andrea.rantin@Innuvatech.com>
sentence=Simple and User friendly library to use the PatchugoLite board
paragraph=For easy and immediate developement
category=Device Control
url=https://github.com/Innuvatech/Patchugo_Lite
architectures=*
includes=patchugo_lite.h
depends=Patchugo_Core